### ISSUE TITLE
test for `get_edges` and `interventions` -- watch for side effects or reallocation of memory. 

### ISSUE THREAD

**Issue by josephdviviano** [Bertinus/FLeCS#26]

**Comment by josephdviviano** [comment]
watch for ADAM momentum updates!

**Comment by Bertinus** [comment]
Problems may happen when the edge parameters are set to trainable (c.f. your comment about Adam above)

**Comment by Bertinus** [comment]
Ideally, write a test in `FLeCS/test/test_intervention.py`

**Comment by Bertinus** [comment]
I rthink you need to re-initialize the optimizer whenever you intervene on the cell (because the set of parameters has changed)
