### ISSUE TITLE
Review EdgeSet, NodeSet, CellPopulation files 

### ISSUE THREAD

**Issue by josephdviviano** [Bertinus/FLeCS#4]
Use self-documenting style when possible, also all classes have docstrings.

**Comment by Bertinus** [comment]
@josephdviviano 

There is now a simple example for defining a custom CellPopulation class, and simulating trajectories with it. (see https://github.com/Bertinus/FLeCS/blob/d0f114703e2267ed09d8e5158a3b3ef6719140f7/flecs/cell_population.py#L119)

I removed the cell_factory.py file as I moved all the logic directly into the CellPopulation class.
