### ISSUE TITLE
Add protein binding information from the String database

### ISSUE THREAD

**Issue by Bertinus** [Bertinus/FLeCS#9]

**Comment by josephdviviano** [comment]
E.g.,: https://stringdb-static.org/download/protein.physical.links.detailed.v11.5/9606.protein.physical.links.detailed.v11.5.txt.gz

from https://string-db.org/cgi/download?sessionId=byMHyfAaukUX&species_text=Homo+sapiens

**Comment by Bertinus** [comment]
Idea: Add an option in the `load_interaction_data` method [link](https://github.com/Bertinus/FLeCS/blob/b2d292a31f3b24ae1a0e04412efbf9628e1aadcc/flecs/data/interaction_data.py#L382)

**Comment by Bertinus** [comment]
Optional: download protein sequences from StringDB and make it part of FleCS. That way, protein sequences will be readily available in case people want to use this information to perform simulations

**Comment by Bertinus** [comment]
Could be 2 steps:
1/ Add an option to load String on its own
2/ Work on the pairing of String with one the GRNs already available (e.g. Fantom5)

**Comment by Bertinus** [comment]
I'll start working on step 2 ("Work on the pairing of String with one the GRNs already available")

**Comment by Bertinus** [comment]
Step 2 is handled now.
